#!/usr/bin/env bash
# Create the release archive file on Windows.
branchname=$(git rev-parse --abbrev-ref HEAD)
if [ $branchname = "main" ]; then
	exec powershell.exe -ExecutionPolicy RemoteSigned -File 'hooks\make-pkg.ps1'
fi
